package org.alfresco.contentlake.syncer.service;

import jakarta.enterprise.context.ApplicationScoped;
import org.alfresco.contentlake.syncer.model.api.RuntimeSettingsResponseDTO;
import org.alfresco.contentlake.syncer.model.api.UpdateRuntimeSettingsRequestDTO;
import org.eclipse.microprofile.config.inject.ConfigProperty;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

@ApplicationScoped
public class RuntimeSettingsService {

    @ConfigProperty(name = "syncer.runtime.root")
    String runtimeRoot;

    @ConfigProperty(name = "quarkus.http.port")
    int httpPort;

    @ConfigProperty(name = "syncer.ui.open-browser-on-startup", defaultValue = "true")
    boolean openBrowserOnStartup;

    @ConfigProperty(name = "syncer.storage-root")
    String dataStorageRoot;

    @ConfigProperty(name = "syncer.logs.dir")
    String logsDir;

    @ConfigProperty(name = "syncer.data-dir")
    String dataDir;

    @ConfigProperty(name = "syncer.jobrunr.data-dir")
    String jobrunrDataDir;

    public RuntimeSettingsResponseDTO load() {
        Path configFile = configFilePath();
        return new RuntimeSettingsResponseDTO(
                httpPort,
                openBrowserOnStartup,
                normalizePath(dataStorageRoot),
                normalizePath(logsDir),
                normalizePath(dataDir),
                normalizePath(jobrunrDataDir),
                normalizePath(configFile.toString()),
                Files.exists(configFile),
                true
        );
    }

    public RuntimeSettingsResponseDTO save(UpdateRuntimeSettingsRequestDTO request) {
        if (request == null) {
            throw new IllegalArgumentException("Settings payload is required");
        }
        if (request.httpPort == null || request.httpPort < 1 || request.httpPort > 65535) {
            throw new IllegalArgumentException("httpPort must be between 1 and 65535");
        }
        if (request.openBrowserOnStartup == null) {
            throw new IllegalArgumentException("openBrowserOnStartup is required");
        }
        if (request.dataStorageRoot == null || request.dataStorageRoot.isBlank()) {
            throw new IllegalArgumentException("dataStorageRoot is required");
        }

        Path storageRoot = Path.of(request.dataStorageRoot).toAbsolutePath().normalize();
        List<String> lines = new ArrayList<>();
        lines.add("# Generated by Alfresco Content Syncer Settings");
        lines.add("# Restart the application to apply these changes.");
        lines.add("quarkus.http.port=" + request.httpPort);
        lines.add("syncer.ui.open-browser-on-startup=" + request.openBrowserOnStartup);
        lines.add("syncer.storage-root=" + normalizePath(storageRoot.toString()));

        Path configFile = configFilePath();
        try {
            Files.createDirectories(configFile.getParent());
            Files.write(configFile, lines);
        } catch (IOException e) {
            throw new IllegalStateException("Failed to write runtime settings to " + configFile, e);
        }

        return new RuntimeSettingsResponseDTO(
                request.httpPort,
                request.openBrowserOnStartup,
                normalizePath(storageRoot.toString()),
                normalizePath(logsDir),
                normalizePath(storageRoot.resolve(".syncer-data").toString()),
                normalizePath(storageRoot.resolve("data").toString()),
                normalizePath(configFile.toString()),
                true,
                true
        );
    }

    public Path configDirectoryPath() {
        return Path.of(runtimeRoot).toAbsolutePath().normalize().resolve("config");
    }

    public Path configFilePath() {
        return configDirectoryPath().resolve("application.properties");
    }

    private String normalizePath(String value) {
        return value.replace('\\', '/');
    }
}

